### ISSUE TITLE
Not working with version 7.4.0.

### ISSUE THREAD

**Issue by TheTechOddBug** [elastic/stack-docker#102]
When we try to launch this "installation" using docker-compose.setup.yml and docker-compose.yml, we get all containers in existed mode after a few seconds using $TAG=7.4.0.

**Comment by ovizii** [comment]
I'm wondering about this too - is this repository still up to date seeing that the tag in .env is 6.xxx ? 
is there a more up-to-date docker-compose.yml available?

**Comment by alvinlee001** [comment]
Hi, is this issue solved? Urgent need to use this

**Comment by drewr** [comment]
Sorry for the poor response here. We've been deciding internally how best to support this tool, and are leaning toward sunsetting it. Much of our effort lately has been [Kubernetes-focused](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html). I would use that integration now instead of Docker Swarm. May not be the answer you were hoping for, but long-term it would serve you better.

**Comment by alvinlee001** [comment]
@drewr Thanks for the guidance. I will look into that, is there another repo that is based of kubernetes, which includes autoscaling of the elastic stack? I need to self host the elastic stack on a private server instead, k8 might be an option too.

**Comment by drewr** [comment]
@alvinlee001 Yep, that's the one. Even though it's branded as "Cloud" it's a quick way to stand up ES+Kibana with operator support.
