### ISSUE TITLE
Default Elasticsearch Container does not have enough memory for some ML Jobs

### ISSUE THREAD

**Issue by morgango** [elastic/stack-docker#19]
In 6.1 we introduced [Population Analysis](https://www.elastic.co/guide/en/x-pack/6.1/ml-configuring-pop.html), when I try to do this in stack-docker I get the following error:

![image](https://user-images.githubusercontent.com/3835173/34174134-90230af2-e4bd-11e7-8ac6-d5a28755da50.png)

I believe it needs more memory by default.

**Comment by jarpy** [comment]
Agreed. I'm guessing you have tweaked your local version. What's a good limit?

**Comment by xeraa** [comment]
Related blog post: https://www.elastic.co/blog/smarter-machine-learning-job-placement-in-elasticsearch

I think you are hitting the "By default the native processes associated with ML jobs are allowed to use 30% of memory on the machine." since your machine seems to have 2GB and the ML job can have around 630MB according to your screenshot. So either give more memory to the container or change `xpack.ml.max_machine_memory_percent`.
