### ISSUE TITLE
Might be nice to bake some dashboards into the example

### ISSUE THREAD

**Issue by geekpete** [elastic/stack-docker#31]
So that when you spin up the stack then point a Kibana at it to view stuff, you have some dashboards ready to look at.

**Comment by fxdgear** [comment]
@geekpete Thanks for your issue. 

I think maybe you're asking this question due to a bug that's already been address? 

The way it works now is each beat will install their own dashboards. Once you log into Kibana (you have to unfortunately select a default index, but then you can nav to the "Dashboards" and "visualization" tabs in Kibana and see that they are all there. 

If you're continuing to have problems with this, please re-open the ticket and I'll help debug the problem with you. 

Thanks
