### ISSUE TITLE
Pick version and component 

### ISSUE THREAD

**Issue by tahaderouiche** [elastic/stack-docker#48]
Few points based on my usage:

1. It would be nice to add clear examples on how to launch a specific version in readme:
`TAG=6.3.1 docker-compose -f setup.yml up`
This will require a change in setup.yml , to pass `TAG` as an ENV variable as well.

2. Also would be possible to setup only some components using just arguments.
Similar to 
`docker-compose up -d elasticsearch kibana` , have something to limit the setup to only some components of the stack (kibana and elasticsearch). 
It is now possible by editing `setup.sh` to only include `setup_kibana` and comment other parts. But was wondering if there is a way to make it simpler using only ENV variables (maybe).
Maybe have that documented somewhere in the readme would help as well.

3. Would be great to specify the url of elasticsearch: `https://localhost:9200` (since kibana is on http but not elasticsearch). It can be a bit confusing.

**Comment by fxdgear** [comment]
Good points and not points lost on me! 

I have more ideas going forward on how to make this more modular.

1. Agreed,. Though I wouldn't do it there I'd change the `.env` so that the envs get carrid through into the "Docker in Docker" approach for setups. 

2. Instead of this I'm thinking about chaining together multiple docker-compose files. It would be nice ot have dedicated usecases of the Elastic Stack and it'd be nice to __not__ default to everything. But instead default to a usecase. And then the more you want to add on to that usecase the more "docker-compose" files are needed. logging, apm, whatever...

3. I'm not sure I follow, what url would you want to use for Elasticsearch? 
are you talking more about https vs http? If so, I'm going to say no, http for elasticsearch is not something I'm going to promote. It's easy enough to change it locally if you want. But I'm not going to document how to do it. I want to instill good practices of security by default. The __only__ reason we don't enable https by dfault with kibana is because it uses a self signed cert, not all browsers make it easy to navigate to a page using a self signed cert. I know chrome does, but not every browser is like that.IMO a better approach would be installing the self signed cert but I didn't think that was in the scope of this project.

**Comment by tahaderouiche** [comment]
@fxdgear , thanks for feedback. On these 3 points:

1. Wonderful. Would be great to have that. I've never seen this before(Docker in Docker), curious to check how this is implemented.
2. That sounds like a very good direction. As use cases will take some time to be fully mature, IMO a good starting point would be to select a subset of the components to be easily picked without too much tweaking scripts and compose files making the experience smoother (with some sample commands in readme to achieve that).
3. Yes, I was referring to http vs https. I completely agree with you as this should provide a smooth and quick starting point. The way it is now definitely does that.
