### ISSUE TITLE
Container setup_elasticsearch Vs elasticsearch

### ISSUE THREAD

**Issue by tahaderouiche** [elastic/stack-docker#49]
I am not sure I understand the difference between the containers `setup_xxxx` and `xxxx`.
Example:  `setup_elasticsearch` and `elasticsearch` .
For example `setup.sh` tries to restart `elasticsearch` but only `setup_elasticsearch` is available at that stage.
Also, after setup and run, we end up with 2 containers per component. Exp: 2 for elasticsearch, 2 for kibana, etc.

**Comment by fxdgear** [comment]
@tahaderouiche thanks for the ticket. 

The reason for the `setup_*`vs the non setup container is because there's a setup that needs to happen for each component. For example setting up ES goes through the process of creating keychains, SSL certs and keystores. During this process we do not need elasticsearch running. Also during the running of Elasticsearch we do not need to have setup scrips. If there's some incorrect volume mounting I'll change it. Sorry if tha's confusing this was a long running PR. 

After setup runs it is expected to have a "dead" setup container cause it ran and now it's done it's job. You are free to delete the setup containers when complete. They aren't needed anymore. 

The idea is that each container does a specific job. 

* run elasticsearch
* setup filebeat
* etc...

I'm not dual purposing containers here. 

I hope this helps explain

**Comment by tahaderouiche** [comment]
Thanks @fxdgear for the clarification , that makes it clear now. I guess the only thing missing now is to 
update the reference to `setup_elasticsearch` in [setup.sh](https://github.com/elastic/stack-docker/blob/master/scripts/setup.sh#L17). I can raise a PR for that. 
Not sure if it makes sense to clean the `setup_xxx` after the initial setup, or whether it is important to keep them. Maybe something to look for in the future.
