### ISSUE TITLE
Using Apache 2.0 as License

### ISSUE THREAD

**Issue by rajiff** [elastic/stack-docker#57]
By following the setup, we get installed, but it has a 14 day license and if it expires, we cannot use the setup? 

Please document if possible to use Apache license even if it means reduced features

**Comment by xeraa** [comment]
Once the trial has ended you can keep using the setup, but the commercial features will be in [degraded mode](https://www.elastic.co/guide/en/elastic-stack-overview/current/license-expiration.html).

The assumption when we built that setup was to show as many features as possible, so it's probably not all that simple to turn this off. Here are some quick pointers:

1. We are activating the trial in https://github.com/elastic/stack-docker/blob/master/config/elasticsearch/elasticsearch.yml#L9. If you comment out that line, you should only get `basic`, which includes only the free features (not all of them are OSS). However, some steps will fail afterwards, since you won't be able to create users.
2. You could try to switch out all `images` to use the OSS ones in the [docker-compose.setup.yml](https://github.com/elastic/stack-docker/blob/master/docker-compose.setup.yml) and [docker-compose.yml](https://github.com/elastic/stack-docker/blob/master/docker-compose.yml). The [Elasticsearch setup already checks if X-Pack is available](https://github.com/elastic/stack-docker/blob/master/scripts/setup-elasticsearch.sh#L10). I'm not sure if that's enough or if you need to make additional changes, but that should be a solid starting point if you want to get an OSS setup.

**Comment by fxdgear** [comment]
@rajiff if you have any other questions please feel free to reopen this issue. 

Thanks
